name: redis-ai-java
services:
  jupyter:
    build:
      context: ..
      dockerfile: ./jupyter/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    env_file:
      - .env
    volumes:
      - ./:/home/jovyan/
      - ./resources:/home/jovyan/resources
  redis-java:
      image: redis/redis-stack:latest
      ports:
        - "6379:6379"  # Redis database port
        - "8001:8001"  # RedisInsight port
      volumes:
        - redis-data:/data  # Persist Redis data

volumes:
  redis-data: